// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuitosParaMuitos.Models;

namespace MuitosParaMuitos.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MuitosParaMuitos.Models.Empregado", b =>
                {
                    b.Property<int>("EmpregadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<int>("Idade");

                    b.Property<string>("Nome");

                    b.HasKey("EmpregadoId");

                    b.ToTable("Empregados");
                });

            modelBuilder.Entity("MuitosParaMuitos.Models.EmpregadoTrabalho", b =>
                {
                    b.Property<int>("EmpregadoId");

                    b.Property<int>("TrabalhoId");

                    b.Property<int>("CargaHoraria");

                    b.HasKey("EmpregadoId", "TrabalhoId");

                    b.HasIndex("TrabalhoId");

                    b.ToTable("EmpregadoTrabalhos");
                });

            modelBuilder.Entity("MuitosParaMuitos.Models.Trabalho", b =>
                {
                    b.Property<int>("TrabalhoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("TrabalhoId");

                    b.ToTable("Trabalhos");
                });

            modelBuilder.Entity("MuitosParaMuitos.Models.EmpregadoTrabalho", b =>
                {
                    b.HasOne("MuitosParaMuitos.Models.Empregado", "Empregado")
                        .WithMany("EmpregadoTrabalhos")
                        .HasForeignKey("EmpregadoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MuitosParaMuitos.Models.Trabalho", "Trabalho")
                        .WithMany("EmpregadoTrabalhos")
                        .HasForeignKey("TrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
